server:
  port: 8083
  error:
    whitelabel:
      enabled: false
    include-stacktrace: ALWAYS
spring:
  main:
    allow-circular-references: true
  application:
    name: system-administration
  datasource:
    username: admin
    password: admin_password
    url: jdbc:postgresql://localhost:5432/system-administration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
