package com.microservice.opportunitymanagement.business.entities;

import com.microservice.opportunitymanagement.utils.constants.OpportunityManagementConstants;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Embedded;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.AttributeOverride;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "opportunity")
public class Opportunity {

    @Id
    @Column(name = OpportunityManagementConstants.OPPORTUNITY_SEQUENCE_ID)
    @Schema(description = "Automatically generated by the system.")
    @SequenceGenerator(
            name = OpportunityManagementConstants.OPPORTUNITY_SEQUENCE_ID,
            sequenceName = OpportunityManagementConstants.OPPORTUNITY_SEQUENCE_ID
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = OpportunityManagementConstants.OPPORTUNITY_SEQUENCE_ID
    )
    private Integer opportunitySequenceId;

    @Column(name = "status")
    private String status;

    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "clientName", column = @Column(name = "client_name")),
            @AttributeOverride(name = "clientEmail", column = @Column(name = "client_email")),
            @AttributeOverride(name = "clientTelephone", column = @Column(name = "client_telephone"))
    })
    private Client client;

    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "vehicleBrand", column = @Column(name = "vehicle_brand")),
            @AttributeOverride(name = "vehicleModel", column = @Column(name = "vehicle_model")),
            @AttributeOverride(name = "vehicleVersion", column = @Column(name = "vehicle_version")),
            @AttributeOverride(name = "vehicleModelDate", column = @Column(name = "vehicle_model_date"))
    })
    private VehicleOfInterest vehicleOfInterest;

    @Column(name = "store_sequence_id")
    private Integer storeSequenceId;

}
