package com.microservice.opportunitymanagement.business.entities;

import com.microservice.opportunitymanagement.utils.constants.OpportunityManagementConstants;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Embedded;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "opportunity")
public class Opportunity {

    @Id
    @Column(name = OpportunityManagementConstants.OPPORTUNITY_SEQUENCE_ID)
    @Schema(description = "Automatically generated by the system.")
    @SequenceGenerator(
            name = OpportunityManagementConstants.OPPORTUNITY_SEQUENCE_ID,
            sequenceName = OpportunityManagementConstants.OPPORTUNITY_SEQUENCE_ID
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = OpportunityManagementConstants.OPPORTUNITY_SEQUENCE_ID
    )
    private Integer opportunitySequenceId;

    @Column(name = "status")
    private String status;

    @Embedded
    private Client client;

    @Embedded
    private VehicleOfInterest vehicleOfInterest;

    @Column(name = "store_sequence_id")
    private Integer storeSequenceId;

}
