package com.microservice.storemanagement.business.entities;

import com.microservice.opportunitymanagement.business.entities.Opportunity;
import com.microservice.storemanagement.utils.constants.StoreManagementConstants;
import com.microservice.systemadministration.business.entities.User;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import java.util.Set;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "store")
public class Store {

    @Id
    @Column(name = StoreManagementConstants.STORE_SEQUENCE_ID)
    @Schema(description = "Automatically generated by the system.")
    @SequenceGenerator(
            name = StoreManagementConstants.STORE_SEQUENCE_ID,
            sequenceName = StoreManagementConstants.STORE_SEQUENCE_ID
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = StoreManagementConstants.STORE_SEQUENCE_ID
    )
    private Integer storeSequenceId;

    @Column(name = "store_name")
    private String storeName;

    @Column(name = "store_users")
    private Set<User> storeUsers;

    @Column(name = "store_opportunities")
    private Set<Opportunity> storeOpportunities;

}
