server:
  port: 8083
spring:
  application:
    name: administration
  datasource:
    username: admin
    password: admin_password
    url: jdbc:postgresql://localhost:5432/administration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
