server:
  port: 8081
spring:
  application:
    name: resale-management
  datasource:
    username: admin
    password: admin_password
    url: jdbc:postgresql://localhost:5432/resale-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
