server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    include-stacktrace: ALWAYS
spring:
  application:
    name: service-editing-opportunities
  datasource:
    username: admin
    password: admin_password
    url: jdbc:postgresql://localhost:5432/service-editing-opportunities
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
