package com.microservice.systemadministration.business.entities;

import com.microservice.systemadministration.utils.constants.SystemAdministrationConstants;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "profile")
public class Profile {

    @Id
    @Column(name = SystemAdministrationConstants.PROFILE_SEQUENCE_ID)
    @Schema(description = "Automatically generated by the system.")
    @SequenceGenerator(
            name = SystemAdministrationConstants.PROFILE_SEQUENCE_ID,
            sequenceName = SystemAdministrationConstants.PROFILE_SEQUENCE_ID
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = SystemAdministrationConstants.PROFILE_SEQUENCE_ID
    )
    private Integer profileSequenceId;

    @Column(name = "profile_name")
    private String profileName;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(
            name = SystemAdministrationConstants.PROFILE_SEQUENCE_ID,
            referencedColumnName = SystemAdministrationConstants.ROLE_SEQUENCE_ID
    )
    private Role profileRole;

}
