package com.microservice.systemadministration.business.entities;

import com.microservice.systemadministration.utils.constants.SystemAdministrationConstants;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "resale")
public class User {

    @Id
    @Column(name = SystemAdministrationConstants.USER_SEQUENCE_ID)
    @Schema(description = "Automatically generated by the system.")
    @SequenceGenerator(
            name = SystemAdministrationConstants.USER_SEQUENCE_ID,
            sequenceName = SystemAdministrationConstants.USER_SEQUENCE_ID
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = SystemAdministrationConstants.USER_SEQUENCE_ID
    )
    private Integer userSequenceId;

    @Column(name = "user_name")
    @Schema(description = "The name of the user.")
    private String userName;

    @Column(name = "email", unique = true)
    @Schema(description = "The valid email of the user.")
    private String email;

    @Column(name = "password")
    @Schema(description = "The password of the user.")
    private String password;

}
