package com.microservice.systemadministration.business.entities;

import com.microservice.systemadministration.utils.constants.SystemAdministrationConstants;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.FetchType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.Set;

@Getter
@Setter
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "user_table")
public class User {

    @Id
    @Column(name = SystemAdministrationConstants.USER_SEQUENCE_ID)
    @Schema(description = "Automatically generated by the system.")
    @SequenceGenerator(
            name = SystemAdministrationConstants.USER_SEQUENCE_ID,
            sequenceName = SystemAdministrationConstants.USER_SEQUENCE_ID
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = SystemAdministrationConstants.USER_SEQUENCE_ID
    )
    private Integer userSequenceId;

    @Column(name = "user_name")
    @Schema(description = "The name of the user.")
    private String userName;

    @Column(name = "email", unique = true)
    @Schema(description = "The valid email of the user.")
    private String email;

    @Column(name = "password")
    @Schema(description = "The password of the user.")
    private String password;

    @OneToMany(
            fetch = FetchType.EAGER,
            mappedBy = "userSequenceId"
    )
    private Set<Profile> profiles;

    @Column(name = "last_opportunity_received")
    private LocalDateTime lastOpportunityReceived;

    @Column(name = "opportunities_attended_number")
    private Integer opportunitiesAttendedNumber;

    @Column(name = "store_sequence_id")
    private Integer storeSequenceId;

}
